// Generated by build script, do not edit!
#ifndef RC_INVOKED
#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2022 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/buildslave/unity/build";

    extern const char* const UnityVersion = "2021.2.8f1";
    extern const char* const UnityVersionDigits = "2021.2.8";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 8;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.2.8f1_d0e5f0a7b06a";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.2.8f1_d0e5f0a7b06a";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.2.8f1 (d0e5f0a7b06a)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 13690352;

    extern const UInt64 UnityVersionDate = 1641407407;
    extern const char* const UnityVersionBranch = "2021.2/staging";
    extern const char* const UnityVersionDisplay = "2021.2.8f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.2.8f1.4208";
    extern const char* const UnityVersionRevision = "d0e5f0a7b06a";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.2.8f1 (d0e5f0a7b06a)";
    extern const wchar_t* const L_UnityVersion = L"2021.2.8f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2022 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 8
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.2.8f1_d0e5f0a7b06a"
    #define UNITY_VERSION_PARENS_HASH "2021.2.8f1 (d0e5f0a7b06a)"
    #define UNITY_VERSION_BLD 13690352
    #define UNITY_VERSION_WIN "2021.2.8.13690352"

#endif // !RC_INVOKED
